services:
 
  firefox:
    image: "selenium/node-firefox:latest"
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    networks: 
        - seleniumgrid     
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_SCREEN_WIDTH: 1920
      SE_SCREEN_HEIGHT: 1080
      MOZ_HEADLESS_WIDTH: 1920
      MOZ_HEADLESS_HEIGHT: 1080

  chrome:
    image: "selenium/node-chrome:latest"
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    networks: 
        - seleniumgrid        
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_SCREEN_WIDTH: 1920
      SE_SCREEN_HEIGHT: 1080

  hub:
    image: selenium/hub:4
    ports:
      - "4442-4444:4442-4444"
    networks: 
        - seleniumgrid        

networks:
    seleniumgrid:
        name: seleniumgrid
