version: '3.7'

services:

    testrunner:
        image: mendhak/smashtest
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${PWD}/:/code/

networks:
  default:
    external: true
    name: seleniumgrid
